# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['cli/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('examples/*.yml', 'examples'),
        ('README.md', '.'),
    ],
    hiddenimports=[
        'cli.main',
        'cli.config',
        'cli.history',
        'cli.plugins',
        'cli.progress',
        'agents.base',
        'agents.factory',
        'agents.openai_agent',
        'agents.anthropic_agent',
        'agents.local_agent',
        'agents.config',
        'engine.executor',
        'engine.expression_evaluator',
        'engine.results',
        'engine.input_providers.base',
        'engine.input_providers.console',
        'engine.input_providers.file',
        'engine.input_providers.web',
        'engine.input_providers.test',
        'engine.step_handlers.base',
        'engine.step_handlers.agent_handler',
        'engine.step_handlers.condition_handler',
        'engine.step_handlers.interaction_handler',
        'models.state',
        'models.template',
        'models.workflow',
        'pydantic',
        'pydantic_core',
        'pydantic.fields',
        'pydantic.main',
        'pydantic.types',
        'click',
        'pyyaml',
        'yaml',
        'yaml.loader',
        'yaml.dumper',
        'jinja2',
        'jinja2.ext',
        'rich',
        'rich.console',
        'rich.table',
        'rich.progress',
        'openai',
        'openai.api_resources',
        'openai.util',
        'anthropic',
        'anthropic.resources',
        'anthropic.types',
        'httpx',
        'httpx._client',
        'httpx._config',
        'httpx._models',
        'httpx._utils',
        'tenacity',
        'tenacity.wait',
        'tenacity.stop',
        'tenacity.retry',
        'aiohttp',
        'aiohttp.client',
        'aiohttp.web',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'PIL',
        'pytest',
        'setuptools',
        'pip',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='pulsar',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='pulsar',
)