---
name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] Brief description of the feature"
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What's the problem you're trying to solve? What pain point does this address?
      placeholder: "Describe the problem here..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution. How would this feature work?
      placeholder: "Describe your solution here..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "Describe alternatives here..."

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Provide a concrete example of how this feature would be used.
      placeholder: "Describe a use case here..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical/blocking my work
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (small change, < 1 day)
        - Medium (moderate change, 1-3 days)
        - Complex (significant change, 1-2 weeks)
        - Major (large feature, > 2 weeks)

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples that might help.
      placeholder: "Add any additional context here..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched for similar feature requests and couldn't find any
          required: true
        - label: This feature would benefit other users, not just me
          required: true
        - label: I understand this is a suggestion and implementation depends on project priorities
          required: true