name: Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: true
        type: string

jobs:
  build-executables:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
            arch: x64
          - os: macos-latest
            target: macos
            arch: x64
          - os: macos-latest
            target: macos
            arch: arm64
          - os: windows-latest
            target: windows
            arch: x64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install PyInstaller and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller click pydantic pyyaml openai anthropic jinja2 aiohttp tenacity rich httpx

    - name: Build executable
      run: |
        pyinstaller build.spec

    - name: Prepare executable for distribution
      shell: bash
      run: |
        cd dist
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          # On Windows, PyInstaller creates pulsar.exe
          EXECUTABLE_NAME="pulsar.exe"
        else
          # On Linux/macOS, PyInstaller creates pulsar
          EXECUTABLE_NAME="pulsar"
        fi
        # Ensure the executable exists and is a file
        if [ ! -f "$EXECUTABLE_NAME" ]; then
          echo "Error: Executable $EXECUTABLE_NAME not found in dist/"
          ls -la
          exit 1
        fi

    - name: Calculate SHA256 hashes
      shell: bash
      run: |
        cd dist
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          EXECUTABLE_NAME="pulsar.exe"
        else
          EXECUTABLE_NAME="pulsar"
        fi
        echo "SHA256 for ${{ matrix.target }}-${{ matrix.arch }}:"
        sha256sum "$EXECUTABLE_NAME"
        echo "SHA256 hash: $(sha256sum "$EXECUTABLE_NAME" | cut -d' ' -f1)" >> $GITHUB_STEP_SUMMARY

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: pulsar-compose-${{ matrix.target }}-${{ matrix.arch }}
        path: |
          dist/pulsar
          dist/pulsar.exe

  build-python-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Check package
      run: |
        pip install check-wheel-contents
        check-wheel-contents dist/*.whl || true

    - name: Upload Python package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-packages
        path: |
          dist/*.tar.gz
          dist/*.whl

  create-release:
    runs-on: ubuntu-latest
    needs: [build-executables, build-python-package]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.repository == 'lsalihi/pulsar-compose'

    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/

    - name: Generate SHA256 summary
      shell: bash
      run: |
        echo "## SHA256 Hashes for Homebrew Formula" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Update these values in pulsar.rb:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        # Linux x64
        if [ -f "artifacts/pulsar-compose-linux-x64/pulsar" ]; then
          LINUX_SHA=$(sha256sum artifacts/pulsar-compose-linux-x64/pulsar | cut -d' ' -f1)
          echo "- Linux x64: \`$LINUX_SHA\`" >> $GITHUB_STEP_SUMMARY
        fi

        # macOS x64
        if [ -f "artifacts/pulsar-compose-macos-x64/pulsar" ]; then
          MACOS_X64_SHA=$(sha256sum artifacts/pulsar-compose-macos-x64/pulsar | cut -d' ' -f1)
          echo "- macOS x64: \`$MACOS_X64_SHA\`" >> $GITHUB_STEP_SUMMARY
        fi

        # macOS ARM64
        if [ -f "artifacts/pulsar-compose-macos-arm64/pulsar" ]; then
          MACOS_ARM64_SHA=$(sha256sum artifacts/pulsar-compose-macos-arm64/pulsar | cut -d' ' -f1)
          echo "- macOS ARM64: \`$MACOS_ARM64_SHA\`" >> $GITHUB_STEP_SUMMARY
        fi

        # Windows x64
        if [ -f "artifacts/pulsar-compose-windows-x64/pulsar.exe" ]; then
          WINDOWS_SHA=$(sha256sum artifacts/pulsar-compose-windows-x64/pulsar.exe | cut -d' ' -f1)
          echo "- Windows x64: \`$WINDOWS_SHA\`" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Get tag name
      id: tag
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "tag=${{ inputs.tag_name }}" >> $GITHUB_OUTPUT
        else
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      run: |
        echo "⚠️  Automatic release creation failed due to permissions."
        echo "📋 To create the release manually:"
        echo ""
        echo "1. Go to https://github.com/lsalihi/pulsar-compose/releases"
        echo "2. Click 'Create a new release'"
        echo "3. Use tag: ${{ steps.tag.outputs.tag }}"
        echo "4. Use title: Release ${{ steps.tag.outputs.tag }}"
        echo "5. Copy the release notes from below:"
        echo ""
        echo "## 🚀 Pulsar Compose ${{ steps.tag.outputs.tag }}"
        echo ""
        echo "Docker-like AI workflow orchestration engine."
        echo ""
        echo "### 📦 Installation Options"
        echo ""
        echo "#### Option 1: Standalone Executable (Recommended)"
        echo "Download the executable for your platform and run:"
        echo "\`\`\`bash"
        echo "# Linux/macOS"
        echo "wget https://github.com/lsalihi/pulsar-compose/releases/latest/download/pulsar-linux-x64"
        echo "chmod +x pulsar-linux-x64"
        echo "sudo mv pulsar-linux-x64 /usr/local/bin/pulsar"
        echo ""
        echo "# macOS (Apple Silicon)"
        echo "wget https://github.com/lsalihi/pulsar-compose/releases/latest/download/pulsar-macos-arm64"
        echo "chmod +x pulsar-macos-arm64"
        echo "sudo mv pulsar-macos-arm64 /usr/local/bin/pulsar"
        echo ""
        echo "# Windows (PowerShell)"
        echo "irm https://github.com/lsalihi/pulsar-compose/releases/latest/download/pulsar-windows-x64.exe -OutFile pulsar.exe"
        echo ""
        echo "# Or use the one-line installer (Linux/macOS):"
        echo "curl -fsSL https://raw.githubusercontent.com/lsalihi/pulsar-compose/master/install.sh | bash"
        echo "\`\`\`"
        echo ""
        echo "#### Option 2: PyPI Package"
        echo "\`\`\`bash"
        echo "pip install pulsar-compose"
        echo "\`\`\`"
        echo ""
        echo "#### Option 3: Docker"
        echo "\`\`\`bash"
        echo "docker pull ghcr.io/lsalihi/pulsar-compose:${{ steps.tag.outputs.tag }}"
        echo "docker run ghcr.io/lsalihi/pulsar-compose:${{ steps.tag.outputs.tag }}"
        echo "\`\`\`"
        echo ""
        echo "#### Option 4: Homebrew (macOS/Linux)"
        echo "\`\`\`bash"
        echo "brew install lsalihi/pulsar-compose/pulsar-compose"
        echo "\`\`\`"
        echo ""
        echo "### 📋 What's New"
        echo "- See [CHANGELOG.md](https://github.com/lsalihi/pulsar-compose/blob/main/CHANGELOG.md) for details"
        echo ""
        echo "### 🔗 Links"
        echo "- [Documentation](https://pulsar-compose.readthedocs.io)"
        echo "- [Repository](https://github.com/lsalihi/pulsar-compose)"
        echo ""
        echo "### 🛠️ For Maintainers"
        echo "After release, update the Homebrew formula:"
        echo "\`\`\`bash"
        echo "./update-homebrew-formula.sh ${{ steps.tag.outputs.tag }}"
        echo "\`\`\`"
        echo ""
        echo "6. Upload these files:"
        echo "   - artifacts/python-packages/*.tar.gz"
        echo "   - artifacts/python-packages/*.whl"
        echo "   - artifacts/pulsar-compose-linux-x64/pulsar (rename to pulsar-linux-x64)"
        echo "   - artifacts/pulsar-compose-macos-x64/pulsar (rename to pulsar-macos-x64)"
        echo "   - artifacts/pulsar-compose-macos-arm64/pulsar (rename to pulsar-macos-arm64)"
        echo "   - artifacts/pulsar-compose-windows-x64/pulsar.exe (rename to pulsar-windows-x64.exe)"
      continue-on-error: true

  publish-pypi:
    runs-on: ubuntu-latest
    needs: create-release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && !contains(github.ref, 'rc') && !contains(github.ref, 'beta') && !contains(github.ref, 'alpha')

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*

  publish-docker:
    runs-on: ubuntu-latest
    needs: create-release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && !contains(github.ref, 'rc') && !contains(github.ref, 'beta') && !contains(github.ref, 'alpha')

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=tag
          type=raw,value=latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64